// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTWAqmAvbfI5Z2gXGBUmzkehDL1-n8alk',
    appId: '1:796128545878:web:93f1f565a996d1427d3ff7',
    messagingSenderId: '796128545878',
    projectId: 'shopping-app-92fdd',
    authDomain: 'shopping-app-92fdd.firebaseapp.com',
    storageBucket: 'shopping-app-92fdd.appspot.com',
    measurementId: 'G-2FVE5QRLVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjr3sFI3gaU_70j7Jyb6EygSg7LEmzSOQ',
    appId: '1:796128545878:android:ecaabff9b1c5171d7d3ff7',
    messagingSenderId: '796128545878',
    projectId: 'shopping-app-92fdd',
    storageBucket: 'shopping-app-92fdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkKqeo-W51cbHhLrotQ5xn-zT0Jm4mOuk',
    appId: '1:796128545878:ios:c60f2f32066002ed7d3ff7',
    messagingSenderId: '796128545878',
    projectId: 'shopping-app-92fdd',
    storageBucket: 'shopping-app-92fdd.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkKqeo-W51cbHhLrotQ5xn-zT0Jm4mOuk',
    appId: '1:796128545878:ios:cd6c92f6ea165fe37d3ff7',
    messagingSenderId: '796128545878',
    projectId: 'shopping-app-92fdd',
    storageBucket: 'shopping-app-92fdd.appspot.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
